name: Windows Build

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Initialize submodules
        run: git submodule update --init --recursive

      - name: Configure
        run: cmake --preset windows-msvc

      - name: Build
        run: cmake --build --preset windows-msvc-release