name: Windows Build

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Initialize submodules
        run: git submodule update --init --recursive

      - name: Bootstrap Vulkan tools
        shell: pwsh
        run: .\tools\bootstrap-vulkan-tools.ps1

      - name: Bootstrap CUDA Runtime
        shell: pwsh
        run: .\tools\bootstrap-cuda.ps1

      - name: Configure
        run: cmake --preset windows-msvc

      - name: Build
        run: cmake --build --preset windows-msvc-release